function [ ] = AmHlib_OleAutomation_PPT_GenVBAcode(	SubPATH, filespec,		...
						hDomain,	hTopoGrd, hTopoIndi, h2DGrd, h2DIndi)
	% sHeader: 이미지 파일 이름의 앞단 헤더
% ppt 의 개발도구/visual basic 에서 구동시킬 수 있는 VBA 소스코드 작성
% 이것은 위에 있는 maker(이건 slide 및 ppt를 직접 생성함)와 달리, ppt에서
%	실행시켜야만 하는 VBA 를 작성해 주는 것임.

%	if isempty(strfind(fname, '.dat')), return; end;% *.dat 확장자에 대해서만!
%	if nargin<2, SpI		=	2000; end;			% 비어 있으면 default로.
%	if nargin<3, chanlist	=	chan32; end;		% 비어 있으면 default로.

[	fullPATH, Regulation, channame, removech, dataname, trialname, subname,	...
	Freqs, fName, m, ki, cedPATH	]	=	A_globals_AmH();

	% VHDR 파일을 생성한다.
	fvba		=	[ fullPATH '/' SubPATH '/' filespec '.bas' ];	 % 파일 path
	fVBA		=	fopen(fvba, 'w');
	fprintf('Generating PPT-VBA file to %s\n', regexprep(fvba, '\\\\', '/'));

	fullPATH	=	strsplit(fullPATH, '/');
	fullPATH	=	[ 'x:\\\\' char(fullPATH(end)) ];		% windows용 path구성

	% header VBA 코드를 작성한다.	%-[
	VBAhead		=	['Sub AmHlib_import_ImageList()\n'						...
'\n'																		...
'Dim oSld As Slide\n'														...
'Dim oPic As Shape\n'														...
'\n'																		...
''' Edit these to suit:\n'													...
'sfullPATH\t\t=\t"' fullPATH '"\n'											...
'Regulation\t\t=\t"' Regulation '"\n'									...
'Dim\tTrialN\n'																...
'\tTrialN\t\t=Array(' strjoin(regexprep(dataname, '(.+)', '"$1"'), ', ') ')\t'' nation\n' ...
'Dim\tTrialP\n'																...
'\tTrialP\t\t=Array(' strjoin(regexprep(trialname, '(.+)', '"$1"'), ', ') ')\t\t\t\t\t\t\t'' prepered\n'			...
'Dim\tfName\n'																...
'\tfName\t\t=Array(' strjoin(regexprep(fName, '(.+)', '"$1"'), ', ') '\t\t\t)\t\t\t\t\t\t\t'' frequency\n'				...
'Dim\tSubName\n'															...
'\tSubName\t\t=Array(\t' strjoin(regexprep(subname, '(.+)', '"$1"'), ', ') '\t)\n'	...
'\n'																		...
'mxSlideW\t\t=\t4032\n'														...
'mxSlideH\t\t=\t4032\n'														...
'\n'																		...
'mxHorzCnt\t\t=\t8\t\t\t\t\t\t\t\t\t'' 가로에 놓을 이미지 수\n'				...
'\t\t\t\t\t\t\t\t\t\t\t\t\t\t'' 세로는 전체 갯수에 따름\n'					...
'mxImageW\t\t=\t1200\t'' 조사결과 1200 px: matlab에서 생성한 이미지의 크기\n' ...
'mxImageH\t\t=\t900\t\t'' 조사하니, 900 px\n'								...
'ImageW\t\t\t=\tmxSlideW / mxHorzCnt\t\t\t\t'' 가로 8장\n'					...
'ImageH\t\t\t=\tImageW * mxImageH / mxImageW\t\t'' 비율유지 & 세로 4 구성\n' ...
'ImgYgap\t\t\t=\t40\t\t\t\t\t\t\t\t\t'' 세로 그림간 여유\n'					...
'ImageX\t\t\t=\t0\t\t\t\t\t\t\t\t\t'' 첫 이미지 시작위치\n'					...
'ImageY\t\t\t=\t(ImageH + ImgYgap) * 4\t\t\t\t'' 첫 이미지 시작위치\n'		...
'\n'																		...
'GrandX\t\t\t=\tImageW\t\t\t\t\t\t\t\t'' 가로 2번째 위치\n'					...
'GrandY\t\t\t=\tImageH * 2\t\t\t\t\t\t\t'' 세로 2번째 위치\n'				...
'\n'																		...
'ActivePresentation.PageSetup.SlideWidth\t\t=\tmxSlideW\t'' 가로: 8장\n'	...
'ActivePresentation.PageSetup.SlideHeight\t=\tmxSlideH\t'' 세로: 4장\n'		...
'\n'																		...
'nSlide\t\t\t=\tActivePresentation.Slides.Count + 1\t\t'' 다음 슬라이드 부터\n' ...
'\n'																		...
'For Each sTrlN In TrialN\n'												...
'For Each sTrlP In TrialP\n'												...
'\n'																		...
'\tHorCnt\t\t\t=\t0\t\t'' 가로에 놓을 이미지 갯수\n'						...
'\tPosX\t\t\t=\tImageX\t'' 하나의 이미지가 놓여질 수평 좌표\n'				...
'\tPosY\t\t\t=\tImageY\n'													...
'\n'																		...
'\tsSubPATH\t\t=\t"\\\\' regexprep(SubPATH, '/', '\\\\') '"\n'				...
'\tGRDWNAME\t\t=\t"' hDomain '" & "_" & sTrlN & "_" & sTrlP\n'				...
'\n'																		...
'\t'' ----------------------------------------------------------------------\n' ...
'\n'																		...
	];	%-]
	% topo 용 VBA 코드를 작성한다.	%-[
	VBAtopo	=	[															...
'\t'' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n' ...
'\t'' 우선 TOPO를 작성한다: 단, 헤더 정보가 empty 이면 생략한다.\n'			...
'\tSet oSld\t\t=\tActivePresentation.Slides.Add(nSlide, ppLayoutBlank)\n'	...
'\t'' title text box 달기\t\t\t\t\t\t''-[\n'								...
'\tSet\tMainBox\t\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\t10,\t\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\t10,\t\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tmxSlideW-20,\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH*1).TextFrame.TextRange\n'			...
'\t'' Set contents\n'														...
'\tMainBox.Text\t=\t"TOPO for " & GRDWNAME\n'								...
'\n'																		...
'\t'' Set format\n'															...
'\tMainBox.Font.Bold=\tmsoFalse\n'											...
'\tMainBox.Font.Name=\t"Calibri"\n'											...
'\tMainBox.Font.Size=\t192\n'												...
'\tMainBox.ParagraphFormat.Alignment\t=\tppAlignCenter\t''-]\n'				...
'\t'' grand average 먼저 올릴 것.\t''-[\n'									...
'\tGRD_IMAG\t\t=\tsfullPATH & sSubPATH & "\\\\' hTopoGrd '" & "_" & GRDWNAME\n'	...
'\n'																		...
'\tSet oPic\t\t=\toSld.Shapes.AddPicture(\t\t\t\t\t\t\t\t\t_\n'				...
'\t\t\t\t\t\t\tFileName\t\t\t:=\tGRD_IMAG & ".jpg",\t\t\t_\n'				...
'\t\t\t\t\t\t\tLinkToFile\t\t\t:=\tmsoFalse,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tSaveWithDocument\t:=\tmsoTrue,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tGrandX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tGrandY,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH\t)\n'								...
'\n'																		...
'\t'' 설명용 text box 달기\n'												...
'\tSet\tGrdBox\t\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tGrandX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tGrandY+ImageH-30,\t\t\t_\n'					...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImgYgap).TextFrame.TextRange\n'			...
'\t'' Set contents\n'														...
'\tGrdBox.Text\t\t=\t"Grand Average"\n'										...
'\n'																		...
'\t'' Set format\n'															...
'\tGrdBox.Font.Bold=\tmsoFalse\n'											...
'\tGrdBox.Font.Name=\t"Calibri"\n'											...
'\tGrdBox.Font.Size=\tImgYgap\n'											...
'\tGrdBox.ParagraphFormat.Alignment\t=\tppAlignCenter\t''-]\n'				...
'\tFor Each sSub In SubName\t'' TOPO 용 slide 구성 -[\n'					...
'\t\tWORKNAME\t=\tsSub & "_" & sTrlN & "_" & sTrlP\n'						...
'\t\tINP_IMAG\t=\tsfullPATH & sSubPATH & "\\\\' hTopoIndi '" & "_" &\t\t\t_\n'	...
'\t\t\t\t\t\t"' hDomain '" & "_" & WORKNAME\n'							...
'\n'																		...
'\t\tIf Not Len(Dir(INP_IMAG & ".jpg")) = 0 Then\t\t\t'' 존재할 때만\n'		...
'\t\tSet oPic\t=\toSld.Shapes.AddPicture(\t\t\t\t\t\t\t\t\t_\n'				...
'\t\t\t\t\t\t\tFileName\t\t\t:=\tINP_IMAG & ".jpg",\t\t\t_\n'				...
'\t\t\t\t\t\t\tLinkToFile\t\t\t:=\tmsoFalse,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tSaveWithDocument\t:=\tmsoTrue,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tPosX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tPosY,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH\t)\n'								...
'\n'																		...
'\t\tBoxText\t=\tsSub\n'												...
'\n'																		...
'\t\tElse\n'																...
'\t\t'' 이미지가 존재하지 않을 경우, text box 달기\n'						...
'\t\tBoxText\t=\tsSub & " Not Exists"\n'								...
'\n'																		...
'\t\tEnd If\n'																...
'\n'																		...
'\t\t'' 설명용 text box의 object 생성\n'									...
'\t\tSet\tIndBox\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tPosX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tPosY+ImageH-30,\t\t\t_\n'					...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImgYgap).TextFrame.TextRange\n'			...
'\n'																		...
'\t\t'' Set contents\n'														...
'\t\tIndBox.Text\t=\tBoxText\n'												...
'\t\t'' Set format\n'														...
'\t\tIndBox.Font.Bold=\tmsoFalse\n'											...
'\t\tIndBox.Font.Name=\t"Calibri"\n'										...
'\t\tIndBox.Font.Size=\tImgYgap\n'											...
'\t\tIndBox.ParagraphFormat.Alignment\t=\tppAlignCenter\n'					...
'\n'																		...
'\t\tHorCnt\t\t=\t( HorCnt+1 ) mod mxHorzCnt\t'' 가로는 8개 단위로 재 계수\n' ...
'\t\tPosX\t\t=\tImageW * HorCnt\n'											...
'\t\tif PosX \t= 0 then\t\t\t\t\t\t'' 슬라이드 끝에 도착 -> 개행!\n'		...
'''\t\t\tPosX\t=\t0\t\t\t\t\t\t\t'' X 좌표는 처음위치로\n'					...
'\t\t\tPosY\t=\tPosY + ImageH + ImgYgap\t\t'' Y 좌표는 다음 줄로\n'			...
'\t\tend if\n'																...
'\n'																		...
'\tNext sSub\t''-]\n'														...
'\tnSlide\t\t\t=\tnSlide + 1\t\t\t\t\t'' 2D는 새 slide 에서\n'				...
'\n'																		...
	];	%-]
	% 2D 그래프용 VBA 코드를 작성한다.	%-[
	VBAgp2d	=	[															...
'\t'' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n' ...
'\t'' 이제는 2D overlap graph를 작성한다.\n'								...
'\tSet oSld\t\t=\tActivePresentation.Slides.Add(nSlide, ppLayoutBlank)\n'	...
'\tHorCnt\t\t\t=\t0\t\t'' 가로에 놓을 이미지 갯수\n'						...
'\tPosX\t\t\t=\tImageX\t'' 하나의 이미지가 놓여질 수평 좌표\n'				...
'\tPosY\t\t\t=\tImageY\n'													...
'\n'																		...
'\t'' title text box 달기\t\t\t\t\t\t''-[\n'								...
'\tSet\tMainBox\t\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\t10,\t\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\t10,\t\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tmxSlideW-20,\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH*1).TextFrame.TextRange\n'			...
'\t'' Set contents\n'														...
'\tMainBox.Text\t=\t"2D overlap for " & GRDWNAME\n'							...
'\n'																		...
'\t'' Set format\n'															...
'\tMainBox.Font.Bold=\tmsoFalse\n'											...
'\tMainBox.Font.Name=\t"Calibri"\n'											...
'\tMainBox.Font.Size=\t192\n'												...
'\tMainBox.ParagraphFormat.Alignment\t=\tppAlignCenter\t''-]\n'				...
'\t'' grand average 2D overlap graph 올릴 것.\t''-[\n'						...
'\tGRD_IMAG\t\t=\tsfullPATH & sSubPATH & "\\\\' h2DGrd '" & "_" & GRDWNAME\n' ...
'\n'																		...
'\tSet oPic\t\t=\toSld.Shapes.AddPicture(\t\t\t\t\t\t\t\t\t_\n'				...
'\t\t\t\t\t\t\tFileName\t\t\t:=\tGRD_IMAG & ".jpg",\t\t\t_\n'				...
'\t\t\t\t\t\t\tLinkToFile\t\t\t:=\tmsoFalse,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tSaveWithDocument\t:=\tmsoTrue,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tGrandX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tGrandY,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH\t)\n'								...
'\n'																		...
'\t'' 설명용 text box 달기\n'												...
'\tSet\tGrdBox\t\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tGrandX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tGrandY+ImageH-30,\t\t\t_\n'					...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImgYgap).TextFrame.TextRange\n'			...
'\t'' Set contents\n'														...
'\tGrdBox.Text\t\t=\t"Grand Average"\n'										...
'\n'																		...
'\t'' Set format\n'															...
'\tGrdBox.Font.Bold=\tmsoFalse\n'											...
'\tGrdBox.Font.Name=\t"Calibri"\n'											...
'\tGrdBox.Font.Size=\tImgYgap\n'											...
'\tGrdBox.ParagraphFormat.Alignment\t=\tppAlignCenter\t''-]\n'				...
'\tFor Each sSub In SubName\t'' 2D overlap graph 용 slide 구성 -[\n'		...
'\t\tWORKNAME\t=\tsSub & "_" & sTrlN & "_" & sTrlP\n'						...
'\t\tINP_IMAG\t=\tsfullPATH & sSubPATH & "\\\\' h2DIndi '" & "_" &\t\t\t_\n' ...
'\t\t\t\t\t\t"' hDomain '" & "_" & WORKNAME\n'							...
'\n'																		...
'\t\tIf Not Len(Dir(INP_IMAG & ".jpg")) = 0 Then\t\t\t'' 존재할 때만\n'		...
'\t\tSet oPic\t=\toSld.Shapes.AddPicture(\t\t\t\t\t\t\t\t\t_\n'				...
'\t\t\t\t\t\t\tFileName\t\t\t:=\tINP_IMAG & ".jpg",\t\t\t_\n'				...
'\t\t\t\t\t\t\tLinkToFile\t\t\t:=\tmsoFalse,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tSaveWithDocument\t:=\tmsoTrue,\t\t\t\t\t_\n'					...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tPosX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tPosY,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImageH\t)\n'								...
'\n'																		...
'\t\tBoxText\t=\tsSub\n'												...
'\n'																		...
'\t\tElse\n'																...
'\t\t'' 이미지가 존재하지 않을 경우, text box 달기\n'						...
'\t\tBoxText\t=\tsSub & " Not Exists"\n'								...
'\n'																		...
'\t\tEnd If\n'																...
'\n'																		...
'\t\t'' 설명용 text box의 object 생성\n'									...
'\t\tSet\tIndBox\t=\toSld.Shapes.AddTextbox(\t\t\t\t\t\t\t\t\t_\n'			...
'\t\t\t\t\t\t\tOrientation\t\t\t:=msoTextOrientationHorizontal,\t_\n'		...
'\t\t\t\t\t\t\tLeft\t\t\t\t:=\tPosX,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tTop\t\t\t\t\t:=\tPosY+ImageH-30,\t\t\t_\n'					...
'\t\t\t\t\t\t\tWidth\t\t\t\t:=\tImageW,\t\t\t\t\t\t_\n'						...
'\t\t\t\t\t\t\tHeight\t\t\t\t:=\tImgYgap).TextFrame.TextRange\n'			...
'\n'																		...
'\t\t'' Set contents\n'														...
'\t\tIndBox.Text\t=\tBoxText\n'												...
'\t\t'' Set format\n'														...
'\t\tIndBox.Font.Bold=\tmsoFalse\n'											...
'\t\tIndBox.Font.Name=\t"Calibri"\n'										...
'\t\tIndBox.Font.Size=\tImgYgap\n'											...
'\t\tIndBox.ParagraphFormat.Alignment\t=\tppAlignCenter\n'					...
'\n'																		...
'\t\tHorCnt\t\t=\t( HorCnt+1 ) mod mxHorzCnt\t'' 가로는 8개 단위로 재 계수\n' ...
'\t\tPosX\t\t=\tImageW * HorCnt\n'											...
'\t\tif PosX \t= 0 then\t\t\t\t\t\t'' 슬라이드 끝에 도착 -> 개행!\n'		...
'''\t\t\tPosX\t=\t0\t\t\t\t\t\t\t'' X 좌표는 처음위치로\n'					...
'\t\t\tPosY\t=\tPosY + ImageH + ImgYgap\t\t'' Y 좌표는 다음 줄로\n'			...
'\t\tend if\n'																...
'\n'																		...
'\tNext sSub\t''-]\n'														...
'\n'																		...
'\tnSlide\t\t\t=\tnSlide + 1\t\t\t\t\t'' 다음 주파수는 새 slide 에서\n'		...
'\n'																		...
	];	%-]
	% tail용 VBA 코드를 작성한다.	%-[
	VBAtail	=	[															...
'Next sTrlP\n'																...
'Next sTrlN\n'																...
'\n'																		...
'End Sub\n'																	...
	];	%-]

	%%--------------------------------------------------
		fprintf(fVBA, VBAhead);
	%%--------------------------------------------------
	if ~isempty(hTopoGrd) && ~isempty(hTopoIndi)			% 비었으면 topo 생략
		fprintf(fVBA, VBAtopo);
	end
	%%--------------------------------------------------
	if ~isempty(h2DGrd) && ~isempty(h2DIndi)				% 비었으면 2D 생략
		fprintf(fVBA, VBAgp2d);
	end
	%%--------------------------------------------------
		fprintf(fVBA, VBAtail);
	%%--------------------------------------------------

	fclose(fVBA);

	return

