#!/bin/sh
cflags=""
ldflags=""
configure_opts="--prefix=${FSLDEVDIR} --enable-static"

configure_script=${FSLDIR}/config/${FSLMACHTYPE}/configure.sh
if [ -f ${configure_script} ]; then
    . ${configure_script}
fi

echo "CFLAGS=\"${cflags}\" CPPFLAGS=\"${cppflags}\" LDFLAGS=\"${ldflags}\" ./configure ${configure_opts}"
CFLAGS="${cflags}" CPPFLAGS="${cppflags}" LDFLAGS="${ldflags}" ./configure ${configure_opts}

