function my_save_fig(f_handle, file_name, width, height)

set(f_handle, ...
    'paperunits','centimeters',...
    'papersize',[width height],...
    'paperposition',[0 0 width height], ...
    'units','centimeters','pos',[-20,0,width,height]);
pause(0.25)
print(f_handle,'-dpdf', file_name)
