function [] = gui_pop()
% Help goes here.
G.fh	=	figure('units','pixels',...
			'position',[300 300 300 230],...
			'menubar','none',...
			'name','Select for multi variables',...
			'numbertitle','off',...
			'resize','off');
G.txVar	=	uicontrol('Style','text', 'String','Variables', ...
			'Unit','pix',				...
			'Position',[10 190 80 25],	...
			'Fontsize',10,...
			'HorizontalAlignment', 'center'...
			);
set(G.txVar,'backgroundcolor',get(G.fh,'color'))
G.var	=	uicontrol('style','pop',...		% select variables
			'unit','pix',...
			'position',[100 200 190 20],...
			'fontsize',10,...
			'fontweight','bold',... 
			'HorizontalAlignment', 'center',...
			'string',{'ERP';'EVK';'TOA';'TOT'},...
			'value',1);

G.txDim	=	uicontrol('Style','text', 'String','Dimension', ...
			'Unit','pix',				...
			'Position',[10 160 80 25],	...
			'Fontsize',10,...
			'HorizontalAlignment', 'center'...
			);
set(G.txDim,'backgroundcolor',get(G.fh,'color'))
G.dim	=	uicontrol('style','pop',...		% selelct dim
			'unit','pix',...
			'position',[100 170 190 20],...
			'fontsize',10,...
			'fontweight','bold',... 
			'string',{'1:280';'2';'3'},...
			'value',1);

G.txInt	=	uicontrol('Style','text', 'String','Index', ...
			'Unit','pix',				...
			'Position',[10 30 80 125],	...
			'Fontsize',10,...
			'HorizontalAlignment', 'center'...
			);
set(G.txInt,'backgroundcolor',get(G.fh,'color'))
G.intv	=	uicontrol('style','list',...		% select interval
			'unit','pix',...
			'position',[100 40 190 120],...
			'fontsize',10,...
			'fontweight','bold',... 
			'max',10, 'min',1,...
			'string',{'1';'2';'3'},...
			'value',1);

G.pb	=	uicontrol('style','push',...
			'unit','pix',...
			'position',[10 10 280 20],...
			'fontsize',12,...
			'fontweight','bold',... 
			'string','SELECT',...
			'callback','uiresume(gcbf)');	% @pb_call);

guidata(G.fh,G)
movegui('center')
uiwait(G.fh);								% polling

%function [] = pb_call(varargin)			% Callback for pushbutton.
G		=	guidata(gcbf);
N		=	get(G.dim,{'string','value'});
N		=	str2double(N{1}(N{2}));

%N = get(G.dim,'value');

% Convert to number.  May not need.  Pass N to a function and display the results.  This is where you can call any function on the path.  I converted to a number, but you may need to keep the string depending on what your function expects.  I have no clue what your function does or what will be in the popup, So I give a general example.
